catch errors that aren't streaming logs

diff --git a/.github/workflows/ephemeral-deploy-pr.yml b/.github/workflows/ephemeral-deploy-pr.yml
--- a/.github/workflows/ephemeral-deploy-pr.yml
+++ b/.github/workflows/ephemeral-deploy-pr.yml
@@ -22,17 +22,18 @@ jobs:
       - name: Set Ephemeral Environment Variables
         run: |
           echo "BACKEND_INSTANCE_NAME=my-backend-ephemeral-pr-${{ github.event.number }}" >> $GITHUB_ENV
-      - name: Print gcloud config
-        run: gcloud config list
-      - name: Print gcloud auth list
-        run: gcloud auth list
-      - name: list env
-        run: env
       - name: Build and push Docker image
         # I've added the || true to the gcloud build step because it returns exit code 1 which fails the pipeline. Currently a bug in github actions https://github.com/orgs/community/discussions/50221
         run: |
           echo "===================="
-          gcloud builds submit --verbosity=debug --config backend/cloudbuild.yaml --substitutions=_BACKEND_INSTANCE_NAME=$BACKEND_INSTANCE_NAME,_PROJECT_ID=${{ vars.GCP_PROJECT_ID }}
+          gcloud builds submit --config backend/cloudbuild.yaml --substitutions=_BACKEND_INSTANCE_NAME=$BACKEND_INSTANCE_NAME,_PROJECT_ID=${{ vars.GCP_PROJECT_ID }} > build.log 2>&1 || true
+        # Check the log file for any errors that aren't about streaming logs
+          if grep -v "The build is running, and logs are being written to the default logs bucket" build.log | grep -q "ERROR"; then
+            echo "An error occurred during the build process."
+            exit 1
+          else
+            echo "The build process completed without errors (excluding any errors about streaming logs)."
+          fi
       - name: Deploy to Cloud Run
         run: |
           gcloud run deploy $BACKEND_INSTANCE_NAME \
